name: CWL Workflow with Singularity

on:
  workflow_dispatch:  # This event allows manual triggering
  push:
    branches:
      - main

jobs:
  test_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Singularity via Conda
        run: |
          conda install -c conda-forge singularity

      - name: Install cwl-runner via pip3
        run: |
          pip3 install cwl-runner
